### ISSUE TITLE
any plane  to  support haxe 3 version ?

### ISSUE THREAD

**Issue by sonygod** [haxe-continuation/haxe-continuation#1]
current I use hx-async instead ,for what it's support haxe 3.
and I got your framework  as well as that ,I want to try until haxe 3 release

**Comment by Atry** [comment]
I guess it's not hard to let haxe-continuation support Haxe 3. Unfortunately, I am not working with Haxe 3, and I cannot make continually testing on Haxe 3.

However, I will accept patches for Haxe 3, if these patch do not break compatibility for Haxe 2.10 or Haxe 2.11
