### ISSUE TITLE
Haxe-continuation with promises

### ISSUE THREAD

**Issue by tiagolr** [haxe-continuation/haxe-continuation#11]
Hi, I'm using haxe-expressjs and a library called sequelize which relies a lot on promises.
Is haxe-continuation a good tool to use with libraries that uses promises?

Considering the code: 

``` haxe
return database.find('something').then(function (i) {
     return database.create('otherthing');
 }).catch(function(e) Promise.reject(e));
```

can haxe-continuation be used with libraries that use promises instead of callback,error? Javascript libraries use them more and more.

Thanks.

**Comment by Atry** [comment]
Yes, you can wrap promises to callback style.

**Comment by tiagolr** [comment]
Thanks, could you add an example, i may return to this sooner or later, currently working with js fibers.
