### ISSUE TITLE
more natural "await .defered" syntax?

### ISSUE THREAD

**Issue by testbird** [haxe-continuation/haxe-continuation#5]
It wasn't that easy to comprehend what this lib does, nor that easy to find this lib in the first place. ;-)

I think you could make it much easier, simply by allowing a more readable syntax
like "await .defered".

Compare to: http://maxtaco.github.io/coffee-script/#iced

**Comment by Atry** [comment]
I know `await`, but I don't know why they need `defer` keyword.

I prefer the following syntax for coffee-script:

```
json = await $.getJSON url
```

**Comment by testbird** [comment]
Hm, I really don't know. Don't you use async() in a similar way?

If you can think of a way that makes it not necessary, the people on the thread following
https://github.com/jashkenas/coffee-script/issues/2662#issuecomment-13046596
may be interested!

**Comment by Atry** [comment]
Yes, `haxe-continuation` allows `var json = getJSON(url).async();` syntax, and you can even use the return value from `.async()` without assigning it to a variable, like `trace(getJSON(url).async().yourProperty);`.

The `.async()` postfix means the same as `await` prefix in C#.

`coffee-script`'s `await` and `defer` are weak. I don't care about that language.

**Comment by testbird** [comment]
Ah, I see, thanks!
Think the difference is in using a "defer" keyword or marking functions "@:cps".

**Comment by SlugFiller** [comment]
"defer" is used to mark where the callback goes into.

It works something like this:

```
var x;
await({
  syncCall();
  cpsFunction(param1, param2, defer(x));
  moreSyncCall();
});
afterCPSSyncCall(x);
```

The syntax

```
await({
  myFunc(param1, param2, defer(x));
});
```

is roughly equivalent to

```
x = myFunc(param1, param2).async();
```

However, it offers the following added capabilities;
Callback is not last parameter:

```
await({
  myCPSFunc(defer(), param1, param2);
});
```

Callback takes multiple parameters:

```
var x, y;
await({
  myCPSFunc(defer(x,y));
});
trace(x+y);
```

Fork multiple calls or perform actions before the callback is called:

```
var x,y;
await({
  myCPSFunc1(defer(x));
  trace("Printed instantly");
  myCPSFunc2(defer(y));
  trace("Also printed instantly");
});
trace("Printed after callback: "+(x+y));
```

So while it adds the need for an assignment, it also offers practical uses which are not possible with the `async` syntax. Although this could be achieved with a helper class:

```
var x,y;
var await = new Await();
myCPSFunc1(await.defer(function(v) {x = v;}));
trace("Printed instantly");
myCPSFunc2(await.defer(function(v) {y = v;}));
trace("Also printed instantly");
await.await().async();
trace("Printed after callback: "+(x+y));
```

**Comment by Atry** [comment]
No, you don't need `defer`. There were two keywords to swap the parameter positions. They are `_` and `callback`.

**Comment by Atry** [comment]
Done by 0e94e5ba8ac76721388b3f298b8a5e2abccd7b8f
