### ISSUE TITLE
Feature request: "fork" like operation but iterations sequential instead of concurrent.

### ISSUE THREAD

**Issue by dionjwa** [haxe-continuation/haxe-continuation#7]
The "fork" feature is pretty great, but sometimes you don't want all the "threads" running concurrently, sometimes you want to step through each element sequentially but asynchronously.  This would be useful.

**Comment by Atry** [comment]
Yes, there is. The normal keyword `for`.

**Comment by dionjwa** [comment]
Whoops, yeah I just tested it. Awesome work!
